services:

  shiny-proxy:
    image: openanalytics/shinyproxy:3.1.0
    restart: on-failure
    networks:
      - bb-net
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # TODO: Consider removing:
      - ./services/shiny-proxy/application.yml:/opt/shinyproxy/application.yml
      # This injection is needed for local development, where I'm testing out
      # shiny proxy in docker stack
      - /Users/cbaker/.Renviron:/opt/shinyproxy/env.txt
    user: root
    environment:
      APP_IMAGE: "${APP_IMAGE}"

  nginx:
    build: ./services/nginx
    restart: always
    networks:
      - bb-net
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/nginx/logs:/nginx/logs
      - ./services/nginx/landing:/www/landing
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - shiny-proxy
#    command: [nginx-debug, "-g", "daemon off;"]

  daily-update-cron:
    image: "${APP_IMAGE}"
    restart: always
    networks:
      - bb-net
    command: ["/bin/bash", "-c", "cron && tail -f /var/log/cron.log"]

  #### Services for dev purposes ####

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    networks:
      - bb-net
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  rstudio-dev:
    image: "${APP_IMAGE}"
    restart: unless-stopped
    networks:
      - bb-net
    ports:
      - 8787:8787
    volumes:
      - .:/home/rstudio/biobuddy-dev
      # Remove this file in the container so I don't activate the renv
      # when I enter the project:
      - /dev/null:/home/rstudio/biobuddy-dev/.Rprofile
      # Preferences
      - ./aws/conf/rstudio-prefs.json:/home/rstudio/.config/rstudio/rstudio-prefs.json
      - ./aws/conf/rstudio-bindings.json:/home/rstudio/.config/rstudio/keybindings/rstudio_bindings.json
    environment:
      ROOT: true
      # Locally in .env
      PASSWORD: "${RSTUDIO_PASSWORD-rstudio}"
    command: ["/init"]

networks:
  bb-net:
