services:

  shiny-proxy:
    image: openanalytics/shinyproxy:3.1.0
    restart: on-failure
    networks:
      - bb-net
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/shiny-proxy/application.yml:/opt/shinyproxy/application.yml
      - ./secrets.txt:/opt/shinyproxy/env.txt
    user: root

  nginx:
    image: nginx:1.27.0
    restart: always
    networks:
      - bb-net
    ports:
      - 80:80
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/landing:/www/landing
      - ./services/nginx/logs:/nginx/logs
    depends_on:
      - shiny-proxy
    command: [nginx-debug, "-g", "daemon off;"]

  # Services for dev purposes. Will restrict incoming traffic on these ports
  # to my IP address (hence no password).
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    networks:
      - bb-net
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # TODO: secrets mapping in, preferences automated, working dir
  # /.rstudio/monitored/user-settings/user-settings
  rstudio-dev:
    image: bb-app
    restart: unless-stopped
    networks:
      - bb-net
    ports:
      - 8787:8787
    environment:
      DISABLE_AUTH: true
      ROOT: true
    command: ["/init"]

networks:
  bb-net:
