services:

  shiny-proxy:
    image: openanalytics/shinyproxy:3.1.0
    restart: on-failure
    networks:
      - bb-net
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # TODO: Consider removing:
      - ./services/shiny-proxy/application.yml:/opt/shinyproxy/application.yml
      # TODO: Note what this injection is for
      - ./secrets.txt:/opt/shinyproxy/env.txt
    user: root

  nginx:
    build: ./services/nginx
    restart: always
    networks:
      - bb-net
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/nginx/logs:/nginx/logs
      - ./services/nginx/landing:/www/landing
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - shiny-proxy
#    command: [nginx-debug, "-g", "daemon off;"]

  #### Services for dev purposes ####

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    networks:
      - bb-net
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  rstudio-dev:
    # Not that big of a deal what version of bb-app is used here, as we map
    # code into container directory.
    image: ghcr.io/crew102/bb-app:latest
    restart: unless-stopped
    networks:
      - bb-net
    ports:
      - 8787:8787
    volumes:
      - .:/home/rstudio/biobuddy-dev
      # Remove this file in the container so I don't activate the renv
      # when I enter the project:
      - /dev/null:/home/rstudio/biobuddy-dev/.Rprofile
      # Preferences
      - ./aws/conf/rstudio-prefs.json:/home/rstudio/.config/rstudio/rstudio-prefs.json
      - ./aws/conf/rstudio-bindings.json:/home/rstudio/.config/rstudio/keybindings/rstudio_bindings.json
    environment:
      ROOT: true
      # Locally in .env
      PASSWORD: "${RSTUDIO_PASSWORD}"
    command: ["/init"]

networks:
  bb-net:
