proxy:
  landing-page: /app_direct/bb-app
  heartbeat-timeout: 60000
  container-wait-time: 60000
  port: 8080
  # Use polished for auth
  authentication: none
  docker:
    internal-networking: true
    container-network: biobuddy_bb-net
  specs:
  - id: bb-app
    container-image: ${APP_IMAGE}
    container-network: biobuddy_bb-net
    # This is needed for local development, b/c we don't get auth to secrets
    # locally in Docker like we do when we run on EC2.
    container-env-file: /opt/shinyproxy/env.txt
#    container-volumes: ["./logs:/home/biobuddy/logs"]
