proxy:
  landing-page: /app_direct/bb-app
  heartbeat-timeout: 60000
  container-wait-time: 60000
  port: 8080
  authentication: none
  docker:
    internal-networking: true
    container-network: biobuddy_bb-net
    port-range-start: 20000
  specs:
  - id: bb-app
    container-image: bf-app
    container-network: biobuddy_bb-net
    container-env-file: /opt/shinyproxy/env.txt
