# Reminder: This whole config is getting mapped into shiny proxy container at
# config up
proxy:
  landing-page: /app_direct/bb-app
  heartbeat-timeout: 60000
  container-wait-time: 60000
  port: 8080
  # Use polished for auth
  authentication: none
  docker:
    internal-networking: true
    container-network: biobuddy_bb-net
  specs:
  - id: bb-app
    container-image: bb-app
    container-network: biobuddy_bb-net
    container-env-file: /opt/shinyproxy/env.txt
#    container-volumes: ["./logs:/home/biobuddy/logs"]
