# Reminder: This whole config is getting mapped into shiny proxy container at
# config up
proxy:
  landing-page: /app_direct/bb-app
  heartbeat-timeout: 60000
  container-wait-time: 60000
  port: 8080
  # Use polished for auth
  authentication: none
  docker:
    internal-networking: true
    container-network: biobuddy_bb-net
  specs:
  - id: bb-app
    container-image: bb-app
    container-network: biobuddy_bb-net
    # This file is mapped from host to shiny proxy container at compose up
    container-env-file: /opt/shinyproxy/env.txt
    # FOR DEV PURPOSES
    # Overwrites code used in containers spun up by shiny proxy (based on bb-app
    # image, which is built off of biobuddy/app/Dockerfile).
    # NOTE THE USE OF DEV dir here, so it's not even true dev stuff, it's
    # dev of dev (used for services testing).
    container-volumes: ["/Users/cbaker/Documents/git-chris/biobuddy/app/dev:/home/app"]
