name: Build and push dependency base image

on:
  workflow_dispatch:
    inputs:
      deps_sha:
        description: 'Commit SHA to build dependency image off of'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Checkout
      run: |
        echo ${{ inputs.deps_sha }}
        git checkout ${{ inputs.deps_sha }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Github CR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build image with primary R, Python, and Debian dependencies
      run: |
        docker build -t ghcr.io/crew102/bb-deps:${{ inputs.deps_sha }} .

    - name: Push image to CR
      run: |
        docker push ghcr.io/crew102/bb-deps:${{ inputs.deps_sha }}

    - name: Create and push deps tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"
        TAG_NAME="deps-built-${{ inputs.deps_sha }}"
        git tag $TAG_NAME
        git push origin $TAG_NAME
