name: Build and test app image

on:
  workflow_dispatch:
    inputs:
      repo-sha:
        description: 'Github commit SHA to build image off of'
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ env.INPUT_REPO-SHA }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    # TODO: Move some of this into metadata action
    - name: Set version envvars
      run: |
        VER=$(head -n 1 version.txt)
        GIT_SHA=$(git rev-parse --short HEAD)
        echo "VERSION=$VER" >> $GITHUB_ENV
        echo "GIT_SHA=$GIT_SHA" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        make img-app-gh
        docker tag bb-app:latest ghcr.io/crew102/bb-app:${{ env.VERSION }}
        docker tag bb-app:latest ghcr.io/crew102/bb-app:${{ env.GIT_SHA }}
        docker tag bb-app:latest ghcr.io/crew102/bb-app:latest

    - name: Test Docker image
      run: |
        docker run --rm bb-app:latest echo "hi there"

    - name: Push Docker image
      run: |
        docker push ghcr.io/crew102/bb-app:${{ env.VERSION }}
        docker push ghcr.io/crew102/bb-app:${{ env.GIT_SHA }}
        docker push ghcr.io/crew102/bb-app:latest
