name: Build and push Docker image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Ensure cache directory exists
      run: mkdir -p /tmp/.buildx-cache

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: make img-deploy

    - name: Test Docker image
      run: |
        docker run --rm bb-app:latest echo "hi there"

    - name: Tag and push Docker image
      run: |
        docker tag bb-app:latest ghcr.io/${{ github.actor }}/bb-app:latest
        docker push ghcr.io/${{ github.actor }}/bb-app:latest
