name: Build and push Docker image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build Docker image
      run: make img-deploy

    - name: Test Docker image
      run: |
        docker run --rm bb-app:latest echo "hi there"

    - name: Tag and push Docker image
      run: |
        docker tag bb-app:latest ghcr.io/${{ github.actor }}/bb-app:latest
        docker push ghcr.io/${{ github.actor }}/bb-app:latest
